name: viraeshop_admin
description: Admin IOS and Android App for Viraeshop
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.4+46
environment:
  sdk: ">=2.12.0 <3.3.10"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  image_picker:
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  firebase_storage: ^11.0.15
  cloud_firestore: ^4.4.4
  random_string:
  shared_preferences: ^2.0.7
  intl:
  jiffy:
  cached_network_image: ^3.1.0
  provider: ^6.0.1
  responsive_framework: ^0.2.0
  flutter_progress_hud: ^2.0.0
  file_picker: ^5.2.5
  loading_indicator: ^3.0.2
  equatable: ^2.0.3
  modal_progress_hud_nsn: ^0.3.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  numeric_keyboard: ^1.1.0
  syncfusion_flutter_pdf: ^20.4.51
  syncfusion_flutter_charts: ^20.4.51
  currency_text_input_formatter: ^2.1.5
  url_launcher: ^6.0.17
  esc_pos_printer: ^4.1.0
  esc_pos_utils: ^1.1.0
  ping_discover_network_forked: ^0.0.1
  #network_info_plus: ^3.0.2
#  printing: ^5.6.6
  pdf: ^3.6.5
  share_plus: ^4.0.10
  tuple: ^2.0.0
  carousel_slider: ^4.0.0
  chat_bubbles: ^1.2.0
  firebase_messaging: ^14.2.6
  flutter_local_notifications: ^9.4.0
  flutter_bluetooth_serial: ^0.4.0
  shimmer: ^2.0.0
  #esc_pos_bluetooth: ^0.4.1
  flutter_linkify: ^5.0.2
  bluetooth_thermal_printer: ^0.0.6
  flutter_styled_toast: ^2.0.0
  amplify_flutter: ^0.6.0
  amplify_auth_cognito: ^0.6.0
  amplify_storage_s3: ^0.6.0
  flutter_pos_printer_platform: ^1.1.0
  file_saver: ^0.1.1
  dart_date: ^1.2.1
  flutter_bloc: ^8.0.0
  viraeshop_api:
#    git:
#      url: https://github.com/viraeshop/viraeshop-api.git
      path: ../../Documents/flutter projects/viraeshop/viraeshop_packages/viraeshop-api
  viraeshop:
#    git:
#      url: https://github.com/viraeshop/viraeshop-bloc.git
    path: ../../Documents/flutter projects/viraeshop/viraeshop_packages/viraeshop-bloc
dependency_overrides:
  xml: ^6.0.1
  firebase_core_platform_interface: ^4.5.1
  intl: ^0.17.0
  viraeshop_api:
    path: ../../Documents/flutter projects/viraeshop/viraeshop_packages/viraeshop-api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.5
  hive_generator: ^2.0.0
  printing: ^5.6.6

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/category/
    - assets/orders/
    - assets/default.jpg
    - assets/vira_shop.png

  fonts:
    - family: SourceSans
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
    - family: TenorSans
      fonts:
        - asset: assets/fonts/TenorSans-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
