name: viraeshop_admin
description: Admin IOS and Android App for Viraeshop
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.8+67
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  image_picker:
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  firebase_storage: ^12.4.9
  cloud_firestore: ^5.6.11
  random_string:
  shared_preferences: ^2.5.3
  intl:
  jiffy:
  cached_network_image: ^3.4.1
  provider: ^6.1.5
  responsive_framework: ^0.2.0
  flutter_progress_hud: ^2.0.2
  file_picker: ^9.2.0
  loading_indicator: ^3.1.1
  equatable: ^2.0.7
  modal_progress_hud_nsn: ^0.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  numeric_keyboard: ^1.1.0
  syncfusion_flutter_pdf: ^29.2.11
  syncfusion_flutter_charts: ^29.2.11
  currency_text_input_formatter: ^2.3.0
  url_launcher: ^6.0.17
#  esc_pos_printer: ^4.1.0
#  esc_pos_utils: ^1.1.0
#  ping_discover_network_forked: ^0.0.1
  #network_info_plus: ^3.0.2
#  printing: ^5.6.6
  pdf: ^3.11.3
  share_plus: ^10.1.4
  tuple: ^2.0.2
  carousel_slider: ^5.1.1
  chat_bubbles: ^1.7.0
  firebase_messaging: ^15.2.9
  flutter_local_notifications: ^19.0.0
#  flutter_bluetooth_serial: ^0.4.0
  shimmer: ^3.0.0
  #esc_pos_bluetooth: ^0.4.1
  flutter_linkify: ^6.0.0
#  bluetooth_thermal_printer: ^0.0.6
  flutter_styled_toast: ^2.2.1
  amplify_flutter: ^2.6.5
  amplify_auth_cognito: ^2.6.5
  amplify_storage_s3: ^2.6.5
  flutter_pos_printer_platform_image_3: ^1.2.4
  flutter_esc_pos_utils: ^1.0.1
  image: ^4.1.3
  file_saver: ^0.2.14
  dart_date: ^1.5.3
  flutter_bloc: ^8.0.0
  blurry_modal_progress_hud: ^1.1.1
  loading_animation_widget: ^1.3.0
  get_time_ago: ^2.3.2
  flutter_svg: ^2.2.0
  viraeshop_api:
#    git:
#      url: https://github.com/viraeshop/viraeshop-api.git
    path: ../viraeshop-api
  viraeshop_bloc:
#    git:
#      url: https://github.com/viraeshop/viraeshop-bloc.git
    path: ../viraeshop-bloc
  badges: ^3.1.2
  printing: ^5.14.2
dependency_overrides:
#  xml: ^6.2.2
#  firebase_core_platform_interface: ^4.5.1
  intl: ^0.20.2
  network_info_plus: ^6.1.4

#  viraeshop_api:
#    path: ../../Documents/flutter projects/viraeshop/viraeshop_packages/viraeshop-api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.5
  hive_generator: ^2.0.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/category/
    - assets/orders/
    - assets/default.jpg
    - assets/

  fonts:
    - family: SourceSans
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
    - family: TenorSans
      fonts:
        - asset: assets/fonts/TenorSans-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
