SELECT TOP (1000) [id]
      ,[productCode]
      ,[buyPrice]
      ,[isInventory]
      ,[productName]
      ,[productPrice]
      ,[originalPrice]
      ,[productImage]
      ,[unitPrice]
      ,[quantity]
      ,[processingStatus]
      ,[receiveStatus]
      ,[createdAt]
      ,[updatedAt]
      ,[availability]
      ,[discount]
      ,[discountPercent]
      ,[adminId]
      ,[orderId]
      ,[supplierId]
      ,[productId]
      ,[isInfinity]
      ,[estimatedTime]
      ,[startTime]
      ,[endTime]
      ,[actualEndTime]
      ,[monitoringStatus]
      ,[startedAt]
  FROM [dbo].[OrderItems]

  Update OrderItems SET  estimatedTime = NULL
  WHERE id = 71
