// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'viraeshop_admin';
  static const String PROJECT_VERSION = '1.2.8+67';
  static const String DEFAULT = 'assets/default.jpg';
}
