// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PROJECT_NAME = 'viraeshop_admin';
  static const String PROJECT_VERSION = '1.2.8+67';
  static const String MONTSERRAT_BOLD = 'Montserrat-Bold';
  static const String MONTSERRAT_REGULAR = 'Montserrat-Regular';
  static const String SOURCESANSPRO_REGULAR = 'SourceSansPro-Regular';
  static const String TENORSANS_REGULAR = 'TenorSans-Regular';
}
