// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoiA-jkFzDVNjX4obb7JY8QDqItTKLV84',
    appId: '1:903623659021:web:10d91ef1e397131f3d8f44',
    messagingSenderId: '903623659021',
    projectId: 'vira-eshop',
    authDomain: 'vira-eshop.firebaseapp.com',
    storageBucket: 'vira-eshop.appspot.com',
    measurementId: 'G-FM6Q0K4B4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN3-r6r-5IuDABAJG9xb0-rFXGe7hiKAY',
    appId: '1:903623659021:android:8a243b5a85c1d9893d8f44',
    messagingSenderId: '903623659021',
    projectId: 'vira-eshop',
    storageBucket: 'vira-eshop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVIx4JdhHhemzMCbGWLXLsGqD8kgUpuIc',
    appId: '1:903623659021:ios:8b235ac56323c9e53d8f44',
    messagingSenderId: '903623659021',
    projectId: 'vira-eshop',
    storageBucket: 'vira-eshop.appspot.com',
    iosBundleId: 'com.viraeshop.admin',
  );
}
