import 'package:flutter/material.dart';

const Color kProductCardColor = Color(0xffB2B1B1);
const Color kMainColor = Color(0xff1de9b6);
const Color kSubMainColor = Color(0xff353d4d);
const Color kBackgroundColor = Color(0xffFFFFFF);
const Color kTextColor1 = Colors.black87;
const Color kSelectedTileColor = Color(0xff575e6b);
const Color kScaffoldBackgroundColor = Color(0xffe6e9ee);
const Color kspareColor = Color(0xffF2F3F8);
const Color kIconColor1 = Color(0xffe87175);
const Color kIconColor2 = Color.fromARGB(255, 238, 124, 37);
const Color kStrokeColor = Color(0xfff7f7f7);
const Color kNewTextColor = Color(0xff437a52);
const Color kNewTextColor1 = Color(0xff08d0c3);
const Color kNewTextColor2 = Color(0xffd62d44);
const Color kRedColor = Color(0xffd72c43);
const Color kBlackColor = Color(0xff171717);
const Color kYellowColor = Color(0xfffed305);
const Color kBlueColor = Color(0xff26308d);
const Color kSpecialBackgroundColor = Color(0xffEBEBEB);
const Color kCategoryBackgroundColor = Color(0xffdbefe3);
const Color kNewYellowColor = Color(0xffffe082);
const Color kTextBoxColor = Color(0xffB8EEDE);
const Color kBrownColor = Color(0xffFFA51F);
const Color kNewBrownColor = Color(0xffD96612);
const Color kBrownColorAccent = Color(0xffFE801E);
const Color kNewMainColor = Color(0xff0cbb8b);